# Add 'repo' label to any root file changes
cosmic-code:
- '*'

# Add dsa label to any change within the 'dsa' package
dsa:
- cosmic-code/dsa/*

# Add dsa label to any change within the 'networking' package
networking:
- networking/*

# Add databas label to any change within the 'database' package
database:
- database/*

# # Add 'test' label to any change to *.spec.js files within the source dir
# test:
# - src/**/*.spec.js

# # Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
# source:
# - any: ['src/**/*', '!src/docs/*']

# # Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
# frontend:
# - any: ['src/**/*.js']
#   all: ['!src/main.js']
