name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank for repoting this to US, We shall analyse it and get back to you at the earliest' first issue"
        pr-message: "Thank for the contribution to this repository, We shall get back to you at the earliest' first pull request"
